version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
        - image: circleci/node:9

jobs:
    checkout_code:
        <<: *defaults
        steps:
            - checkout
            - save_cache:
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
                paths:
                    - ~/repo

    yarn_deps:
        <<: *defaults
        steps:
            - restore_cache:
                name: Restore code cache
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                name: Restore Yarn Package Cache
                key: yarn-cache-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-cache-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules/

    test:
        <<: *defaults
        steps:
            - restore_cache:
                name: Restore code cache
                key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                name: Restore Yarn Package Cache
                key: yarn-cache-{{ checksum "yarn.lock" }}
            - run:
                name: Test
                command: yarn test

workflows:
    version: 2
    test_only:
        jobs:
            - checkout_code
            - yarn_deps:
                requires:
                    - checkout_code
            - test:
                requires:
                    - yarn_deps