version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:9

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - '*'

  npm_deps:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: ~/repo
          paths:
            - 'node_modules/'

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  test_only:
    jobs:
      - checkout_code
      - npm_deps:
          requires:
            - checkout_code
      - test:
          requires:
            - npm_deps
